-- CREATE TABLE account (
--                          account_id VARCHAR(255) PRIMARY KEY,
--                          balance NUMERIC(15,2) NOT NULL
-- );
--
-- CREATE TABLE transfer (
--                           transfer_id VARCHAR(255) PRIMARY KEY,
--                           from_account_id VARCHAR(255) NOT NULL,
--                           to_account_id VARCHAR(255) NOT NULL,
--                           amount NUMERIC(15,2) NOT NULL,
--                           status VARCHAR(50) NOT NULL,
--                           created_at TIMESTAMP NOT NULL,
--                           updated_at TIMESTAMP NOT NULL,
--                           CONSTRAINT unique_transfer_id UNIQUE (transfer_id)
-- );