AWSTemplateFormatVersion: '2010-09-09'
Description: Elastic Beanstalk environment for banking-service
Parameters:
  ApplicationName:
    Type: String
    Default: banking-portfolio
  EnvironmentName:
    Type: String
    Default: banking-env
  InstanceType:
    Type: String
    Default: t3.micro
  SolutionStack:
    Type: String
    Default: 64bit Amazon Linux 2023 v4.7.1 running Docker
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetId1:
    Type: AWS::EC2::Subnet::Id
    Description: First subnet for EB (e.g., us-east-1a)
  SubnetId2:
    Type: AWS::EC2::Subnet::Id
    Description: Second subnet for EB (e.g., us-east-1b)
  ArtifactsBucketName:
    Type: String
    Default: banking-portfolio-artifacts
Resources:
  BankingApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ApplicationName
  EBInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
      Policies:
        - PolicyName: ParameterStoreAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                  - ssm:DescribeParameters
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/banking/rds/*'
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/31588c91-f532-4b02-a6f9-94ba1594321e
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactsBucketName}/*
                  - !Sub arn:aws:s3:::elasticbeanstalk-${AWS::Region}-${AWS::AccountId}/*
  EBInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EBInstanceRole
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${EnvironmentName}-launch-template
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        SecurityGroupIds:
          - !ImportValue banking-portfolio-core:EBSecurityGroupId
        IamInstanceProfile:
          Arn: !GetAtt EBInstanceProfile.Arn
  BankingEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref BankingApplication
      EnvironmentName: !Ref EnvironmentName
      SolutionStackName: !Ref SolutionStack
      OptionSettings:
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: 1
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: 1
        - Namespace: aws:ec2:vpc
          OptionName: VPCId
          Value: !Ref VpcId
        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value: !Join [',', [!Ref SubnetId1, !Ref SubnetId2]]
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SecurityGroups
          Value: !ImportValue banking-portfolio-core:EBSecurityGroupId
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: SingleInstance
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref EBInstanceProfile
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: RDS_ENDPOINT
          Value: !ImportValue banking-portfolio-core:RDSEndpoint
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: KAFKA_BROKER
          Value: !ImportValue banking-portfolio-core:KafkaBroker
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: SPRING_PROFILES_ACTIVE
          Value: docker
        - Namespace: aws:elasticbeanstalk:healthreporting:system
          OptionName: SystemType
          Value: enhanced
Outputs:
  EBEnvironmentUrl:
    Description: URL for banking-env
    Value: !GetAtt BankingEnvironment.EndpointURL